package views.javaFX;

import javafx.fxml.FXML;

import javafx.scene.control.Button;
import engine.GameManager;
import javafx.event.ActionEvent;

import javafx.scene.control.TabPane;

import javafx.scene.control.Label;

import javafx.scene.control.ComboBox;

import javafx.scene.control.Tab;

import javafx.scene.layout.AnchorPane;

import javafx.scene.control.CheckBox;

import javafx.scene.control.TableView;

import javafx.scene.layout.GridPane;
import javafx.stage.FileChooser;
import javafx.stage.Stage;

public class GameController {
	@FXML
	private GridPane gridMainGrid;
	@FXML
	private TabPane tabPaneSettingsTab;
	@FXML
	private Tab tabGameSettings;
	@FXML
	private AnchorPane anchorTabAnchor;
	@FXML
	private CheckBox chkboxGoldFishMode;
	@FXML
	private Label labelScore;
	@FXML
	private ComboBox comboSkin;
	@FXML
	private CheckBox chckboxAnimation;
	@FXML
	private Label labelTilesLeft;
	@FXML
	private Tab tabDictionary;
	@FXML
	private TableView tableDictionary;
	@FXML
	private Tab tableLetters;
	@FXML
	private TableView tableWords;
	@FXML
	private Button btnPrev;
	@FXML
	private Button btnLoadButton;
	@FXML
	private Button btnStart;
	@FXML
	private Label lblCurrentPlayer;
	@FXML
	private Button btnAddPlayer;
	@FXML
	private Button btnUndo;
	@FXML
	private Button btnFlip;
	@FXML
	private Button btnForfiet;
	@FXML
	private Label labelWord;
	@FXML
	private Button bntRollDice;
	@FXML
	private AnchorPane anchorGame;
	
	Stage primaryStage;
	GameManager gameManager;
	
	public GameController(Stage primary, GameManager gm) {
		primaryStage = primary;
		gameManager = gm;
	}

	// Event Listener on ComboBox[#comboSkin].onAction
	@FXML
	public void handleSkinChanged(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on CheckBox[#chckboxAnimation].onAction
	@FXML
	public void handleAnimationCheck(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnPrev].onAction
	@FXML
	public void handlePrevBtnPressed(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnLoadButton].onAction
	@FXML
	public void handleLoadBtnPressed(ActionEvent event) {
		FileChooser fileChooser = new FileChooser();
		fileChooser.setTitle("Open Resource File");
		fileChooser.showOpenDialog(primaryStage);
	}
	// Event Listener on Button[#btnStart].onAction
	@FXML
	public void handleStartBtnPressed(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnAddPlayer].onAction
	@FXML
	public void handleAddPlayerBtnPressed(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnUndo].onAction
	@FXML
	public void handleUndoPressed(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnFlip].onAction
	@FXML
	public void handleFlipPressed(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnForfiet].onAction
	@FXML
	public void handleForfietPressed(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#bntRollDice].onAction
	@FXML
	public void handleRollPressed(ActionEvent event) {
		// TODO Autogenerated
	}
}
