package views.javaFX;

import javafx.fxml.FXML;
import javafx.scene.canvas.Canvas;
import javafx.scene.control.Alert;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.Button;

import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Observable;
import java.util.Observer;

import engine.Game.eGameState;
import gameSettings.Letter;
import gameSettings.Letters;
import gameSettings.Player;
import engine.GameManager;
import javafx.beans.property.DoubleProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.TabPane;
import javafx.scene.control.TableColumn;
import javafx.scene.control.Label;

import javafx.scene.control.ComboBox;
import javafx.scene.control.Tab;

import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.Background;
import javafx.scene.layout.BackgroundFill;
import javafx.scene.control.CheckBox;

import javafx.scene.control.TableView;
import javafx.scene.image.ImageView;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.Pane;
import javafx.scene.layout.StackPaneBuilder;
import javafx.scene.layout.TilePane;
import javafx.scene.paint.Color;
import javafx.stage.FileChooser;
import javafx.stage.Stage;
import javafx.util.Pair;

public class GameController implements Observer {
	@FXML
	private GridPane gridMainGrid;
	@FXML
	private TabPane tabPaneSettingsTab;
	@FXML
	private Tab tabGameSettings;
	@FXML
	private AnchorPane anchorTabAnchor;
	@FXML
	private CheckBox chkboxGoldFishMode;
	@FXML
	private Label labelScore;
	@FXML
	private ComboBox comboSkin;
	@FXML
	private CheckBox chckboxAnimation;
	@FXML
	private Label labelTilesLeft;
	@FXML
	private Tab tabDictionary;
	@FXML
	private TableView tableDictionary;
	@FXML
	private TableView tablePlayers;
	@FXML
	private TableView tableLetters;
	@FXML
	private TableView tableWords;
	@FXML
	private Button btnPrev;
	@FXML
	private Button btnLoadButton;
	@FXML
	private Button btnStart;
	@FXML
	private Label lblCurrentPlayer;
	@FXML
	private Button btnAddPlayer;
	@FXML
	private Button btnUndo;
	@FXML
	private Button btnFlip;
	@FXML
	private Button btnForfiet;
	@FXML
	private Label labelWord;
	@FXML
	private Button bntRollDice;
	@FXML
	private AnchorPane anchorGame;
	@FXML
	private TableColumn<StringProperty, String> tableDictionaryWordColumn;
	@FXML
	private TableColumn<Letter, String> tableLettersLettersColumn;
	@FXML
	private TableColumn<Letter, Number> tableLettersFreqColumn;
	@FXML
	private TableColumn<Player, String> tablePlayersNameColumn;
	@FXML
	private TableColumn<Player, String> tablePlayersTypeColumn;
	@FXML
	private TableColumn<Player, Number> tablePlayersIDColumn;
	@FXML
	private TableColumn<Player, Number> tablePlayersScoreColumn;
	@FXML
	private TableColumn<WordTableData, String> tableWordsWordColumn;
	@FXML
	private TableColumn<WordTableData, String> tableWordsScoreColumn;
	@FXML
	private Pane paneBoard;
	
	Stage primaryStage;
	GameManager gameManager;
	TileController[][] board;
	
	public GameController(Stage primary, GameManager gm) {
		primaryStage = primary;
		gameManager = gm;
	}

	// Event Listener on ComboBox[#comboSkin].onAction
	@FXML
	public void handleSkinChanged(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on CheckBox[#chckboxAnimation].onAction
	@FXML
	public void handleAnimationCheck(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnPrev].onAction
	@FXML
	public void handlePrevBtnPressed(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnLoadButton].onAction
	@FXML
	public void handleLoadBtnPressed(ActionEvent event) {
		if ((gameManager.getCurrentGame() == null) ||
			(gameManager.getCurrentGame().getStatus() != eGameState.RUNNING)) {
			FileChooser fileChooser = new FileChooser();
			fileChooser.setTitle("Open Resource File");
			File file = fileChooser.showOpenDialog(primaryStage);
			
			if (file != null) {
				String input = file.getAbsolutePath();
				try {
					// TODO: Add thread + progress bar
					gameManager.loadGame(input);
					loadContent();
					
				} catch (Exception e) {
					// TODO Auto-generated catch block
					ShowAlert(e.getMessage());
				}
			}
		} else {
			ShowAlert("Can't load during running game");
		}
	}
	private void loadContent() {
		chkboxGoldFishMode.setSelected(gameManager.getCurrentGame().getSettings().getDescriptor().getGameType().isGoldFishMode());

		loadPlayersTable();
		loadLettersTable();
		loadDictionaryTable();
		loadTilesLeftLabel();
		setCurrentPlayer();
		loadWordsTable();
		loadBoard();
	}

	final class WordTableData
	{
		SimpleStringProperty word;
		SimpleStringProperty score;
		int count;
		SimpleStringProperty finalString;
	}
	
	private void loadWordsTable() {
		HashMap<String, WordTableData> words = new HashMap<String, WordTableData>();
		
		List<String> temp = gameManager.getCurrentGame().getCurrentPlayer().getWordsPlayed();
		
		for (String word : temp) {
			if (words.containsKey(word)) {
				words.get(word).count++;
				words.get(word).finalString = new SimpleStringProperty(Integer.toString(
							words.get(word).count) + " * " + word);
			} else {
				WordTableData data = new WordTableData();
				data.word = new SimpleStringProperty(word);
				data.score = new SimpleStringProperty(Integer.toString(gameManager.getCurrentGame().getSettings().getDictionary().getWordSegment(word))
				+ " * " + gameManager.getCurrentGame().getSettings().getLetterScore(word)
				+ " = " + gameManager.getCurrentGame().getSettings().getScore(word));
				
				data.finalString = new SimpleStringProperty(Integer.toString(data.count) + " * " + data.word);
			}
		}

		ObservableList<WordTableData> list = FXCollections.observableArrayList();
		for (WordTableData word : words.values()) {
			list.add(word);
		}
		
		tableWords.setItems(list);
		tableWordsScoreColumn.setCellValueFactory(cellData -> (cellData.getValue().score));
		tableWordsWordColumn.setCellValueFactory(cellData -> (cellData.getValue().finalString));

		
	}

	private void loadPlayersTable() {
		tablePlayers.setItems(gameManager.getCurrentGame().getSettings().getDescriptor().getPlayers().getPlayersList());;
		tablePlayersNameColumn.setCellValueFactory(cellData -> cellData.getValue().getRealName());
		tablePlayersIDColumn.setCellValueFactory(cellData -> (cellData.getValue().getObserveID()));
		tablePlayersTypeColumn.setCellValueFactory(cellData -> (cellData.getValue().getObserveType()));
		tablePlayersScoreColumn.setCellValueFactory(cellData -> (cellData.getValue().getObserveScore()));
	}

	private void loadBoard() {
		paneBoard.getChildren().clear();
		int size = gameManager.getCurrentGame().getBoard().getSize();
		board = new TileController[size][size];
		double height = paneBoard.getHeight() / size;
		double width = paneBoard.getWidth() / size;
		paneBoard.setVisible(true);
		for (int i = 0; i < size; i++) {
			for (int j = 0; j < size; j++) {
				TileController tile = new TileController(this, i, j,
						gameManager.getCurrentGame().getTile(i, j), height, width);
				tile.setVisible(true);
				board[i][j] = tile;
				paneBoard.getChildren().add(tile);
			}
		}
	}

	private void setCurrentPlayer() {
		lblCurrentPlayer.textProperty().set("Current player: " +
				gameManager.getCurrentGame().getCurrentPlayer().getName().get(0));
	}

	private void loadDictionaryTable() {
		List<String> temp = gameManager.getCurrentGame().getSettings().getDictionary().getLeastPopularWords();
		
		ObservableList<StringProperty> list = FXCollections.observableArrayList();
		for (String string : temp) {
			list.add(new SimpleStringProperty(string));
		}
		tableDictionary.setItems(list);
		tableDictionaryWordColumn.setCellValueFactory(cellData -> (cellData.getValue()));
	}

	private void loadLettersTable() {
		List<Letter> letters = gameManager.getCurrentGame().getSettings().getDescriptor().getStructure().getLetters().getLetter();
		ObservableList<Letter> f= FXCollections.observableArrayList();
		
		for (Letter letter : letters) {
			f.add(letter);
		}

		tableLetters.setItems(f);
		tableLettersFreqColumn.setCellValueFactory(cellData -> cellData.getValue().getFreqProperty());
		tableLettersLettersColumn.setCellValueFactory(cellData -> cellData.getValue().getSignProperty());
	}

	private void loadTilesLeftLabel() {
		labelTilesLeft.textProperty().set("Tiles left : " +
				Integer.toString(gameManager.getCurrentGame().getBoard().getTilesLeft()));
		
	}

	// Event Listener on Button[#btnStart].onAction
	@FXML
	public void handleStartBtnPressed(ActionEvent event) {
		
	}
	// Event Listener on Button[#btnAddPlayer].onAction
	@FXML
	public void handleAddPlayerBtnPressed(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnUndo].onAction
	@FXML
	public void handleUndoPressed(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnFlip].onAction
	@FXML
	public void handleFlipPressed(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnForfiet].onAction
	@FXML
	public void handleForfietPressed(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#bntRollDice].onAction
	@FXML
	public void handleRollPressed(ActionEvent event) {
		// TODO Autogenerated
	}
	
	public void ShowAlert(String message) 
	{
		Alert alert = new Alert(AlertType.INFORMATION);
		alert.setTitle("Info");
		alert.setHeaderText(null);
		alert.setContentText(message);
		alert.showAndWait();		
	}

	@Override
	public void update(Observable o, Object arg) {
		for (int i = 0; i < board.length; i++) {
			for (int j = 0; j < board.length; j++) {
				System.out.println("I J " + Integer.toString(i) + Integer.toString(j));
				board[i][j].Refresh();
			}
		}
		
		loadTilesLeftLabel();
		setCurrentPlayer();
	}
}
