package views.javaFX;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import java.util.Iterator;
import java.util.Random;

import engine.GameManager;
import javafx.event.ActionEvent;

import javafx.scene.input.MouseEvent;
import javafx.scene.layout.Background;
import javafx.scene.layout.BackgroundFill;
import javafx.scene.layout.ColumnConstraints;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.Pane;
import javafx.scene.layout.RowConstraints;
import javafx.scene.paint.Color;
import javafx.scene.shape.Rectangle;

public class WordiadaController {
	@FXML
	private GridPane gridBoard;
	@FXML
	private Button loadButton;
	
	private GameManager gameManager;
	
	public WordiadaController(GameManager gm) {
		gameManager = gm;
	}
	// Event Listener on GridPane[#gridBoard].onMouseEntered
	/*@FXML
	public void gridMouseEnteredEvent(MouseEvent event) {
	}*/
	// Event Listener on Button[#loadButton].onAction
	@FXML
	public void handleSubmitButtonAction(ActionEvent event) {
		final int numCols = 50 ;
		final int numRows = 50 ;
		Pane pane = new Pane();
		for (int i = 0; i < numCols; i++) {
			for (int j = 0; i < numRows; j++) {
				pane.getChildren().add(gameManager.getCurrentGame().getBoard().getBoard()[i][j]);
			}
			
		}
		
/*		gridBoard.getColumnConstraints().clear();
		gridBoard.getRowConstraints().clear();
		for (int i = 0; i < numCols; i++) {
			ColumnConstraints colConst = new ColumnConstraints();
			colConst.setPercentWidth(100.0 / numCols);
			gridBoard.getColumnConstraints().add(colConst);
		}
		for (int i = 0; i < numRows; i++) {
			RowConstraints rowConst = new RowConstraints();
			rowConst.setPercentHeight(100.0 / numRows);
			gridBoard.getRowConstraints().add(rowConst);
		}*/
	}
	// Event Listener on Button[#loadButton].onDragDetected
	@FXML
	public void asdf(MouseEvent event) {
		// TODO Autogenerated
	}
}
